<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Report exports too large to build during a request: generated by a queued job, then downloaded by the user
 * who asked for them.
 */
return new class extends Migration
{
    public function up(): void
    {
        $users = config('accounting.users_table', 'users');

        Schema::create('accounting_report_exports', function (Blueprint $table) use ($users): void {
            $table->id();
            $table->foreignId('company_id')->constrained('accounting_companies', indexName: 'acct_report_exports_company_fk')->cascadeOnDelete();
            $table->foreignId('user_id')->constrained($users, indexName: 'acct_report_exports_user_fk')->cascadeOnDelete();
            $table->string('report', 50);
            $table->string('format', 10);
            $table->json('filters')->nullable();
            $table->string('status', 10)->default('queued');
            $table->string('disk', 50)->nullable();
            $table->string('path', 500)->nullable();
            $table->unsignedInteger('rows')->nullable();
            $table->unsignedBigInteger('size')->nullable();
            $table->text('error')->nullable();
            $table->timestamp('started_at')->nullable();
            $table->timestamp('finished_at')->nullable();
            $table->timestamps();

            $table->index(['user_id', 'created_at'], 'acct_report_exports_user_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('accounting_report_exports');
    }
};
