<x-accounting::app-layout title="Move stock">
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 leading-tight">Move stock</h2></x-slot>
    @php($types = ['receipt' => 'Receive stock', 'issue' => 'Issue stock (cost of goods sold)', 'adjustment' => 'Adjust (count difference)', 'transfer' => 'Transfer between warehouses'])
    <div class="py-6"><div class="max-w-4xl mx-auto sm:px-6 lg:px-8 space-y-4">
        @if(session("success"))<div class="rounded-md bg-emerald-50 border border-emerald-200 p-3 text-sm text-emerald-800">{{ session("success") }}</div>@endif
        @if(session("error"))<div class="rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-800">{{ session("error") }}</div>@endif
        <x-accounting::validation-errors />
        <p class="text-sm text-gray-600">Receipts, issues, count adjustments and transfers; the ledger entry is made with the movement.</p>
        <form method="POST" action="{{ route('accounting.inventory.movements.store') }}" class="bg-white shadow rounded-lg p-5 grid gap-4 md:grid-cols-3">
            @csrf
            <label class="text-sm"><span class="text-gray-700">What happened</span><select name="type" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm">@foreach ($types as $key => $label)<option value="{{ $key }}" @selected(old('type', $preset['type']) === $key)>{{ $label }}</option>@endforeach</select></label>
            <label class="text-sm"><span class="text-gray-700">Item</span><select name="item_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"><option value="">Choose…</option>@foreach ($items as $item)@if($item['is_active'])<option value="{{ $item['id'] }}" @selected((string) old('item_id', $preset['item_id']) === (string) $item['id'])>{{ $item['sku'] }} {{ $item['name'] }}</option>@endif @endforeach</select></label>
            <label class="text-sm"><span class="text-gray-700">Warehouse (from, for a transfer)</span><select name="warehouse_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"><option value="">Choose…</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse['id'] }}" @selected((string) old('warehouse_id') === (string) $warehouse['id'])>{{ $warehouse['name'] }}</option>@endforeach</select></label>
            <label class="text-sm"><span class="text-gray-700">To warehouse (transfers only)</span><select name="to_warehouse_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"><option value="">—</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse['id'] }}" @selected((string) old('to_warehouse_id') === (string) $warehouse['id'])>{{ $warehouse['name'] }}</option>@endforeach</select></label>
            <label class="text-sm"><span class="text-gray-700">Date</span><input type="date" name="movement_date" value="{{ old('movement_date', $today) }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"></label>
            <label class="text-sm"><span class="text-gray-700">Quantity (negative = lost, adjustments only)</span><input type="number" step="any" name="quantity" value="{{ old('quantity') }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"></label>
            <label class="text-sm"><span class="text-gray-700">Unit cost (receipts; adjustments: blank = average)</span><input type="number" step="any" name="unit_cost" value="{{ old('unit_cost') }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"></label>
            <label class="text-sm"><span class="text-gray-700">Account (paid from / owed to, cost or gain/loss; not for transfers)</span><select name="offset_account_id" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"><option value="">—</option>@foreach ($accounts as $account)<option value="{{ $account['id'] }}" @selected((string) old('offset_account_id') === (string) $account['id'])>{{ $account['account_code'] }} {{ $account['account_name'] }}</option>@endforeach</select></label>
            <label class="text-sm"><span class="text-gray-700">Reference</span><input name="reference" value="{{ old('reference') }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"></label>
            <label class="text-sm md:col-span-2"><span class="text-gray-700">Notes</span><input name="notes" value="{{ old('notes') }}" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm text-sm"></label>
            <div class="md:col-span-3"><button class="inline-flex items-center px-4 py-2 bg-blue-950 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest">Record</button> <a href="{{ route('accounting.inventory.index') }}" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md font-semibold text-xs uppercase tracking-widest hover:bg-gray-50">Cancel</a></div>
        </form>
    </div></div>
</x-accounting::app-layout>
